spring.application.name=WheelGame
server.port=8082

# PostgreSQL Database Configuration (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.hxvmcurwlsdxnhlfjycc
spring.datasource.password=TeamAfrica12345!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

# Per permettere la creazione delle tabelle automaticamente come su Oracle
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Disabilita prepared statements per compatibilità con il pooler (Supabase/PgBouncer)
spring.jpa.properties.hibernate.prepare_threshold=0
# Ottimizzazione per connessioni pooler (Supabase)
spring.datasource.hikari.maximum-pool-size=10

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=africa.wheel.wheelgame.dto

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Riduzione log per connessione Kafka fallita e tentativi
logging.level.org.apache.kafka.clients.NetworkClient=DEBUG
logging.level.org.apache.kafka.common.security=DEBUG
logging.level.org.springframework.kafka.support.LoggingProducerListener=OFF
spring.kafka.admin.fail-fast=false
spring.kafka.producer.retries=0
spring.kafka.producer.properties.max.block.ms=500
spring.kafka.admin.properties.timeout.ms=500
# logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.kafka.enabled=true
spring.kafka.bootstrap-servers=kafka-falcomarilena-cc94.g.aivencloud.com:25423

# Configurazioni SSL e SASL per Aiven Kafka
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

# Usa il trust-store JKS invece del PEM che dava errore
spring.kafka.ssl.trust-store-type=JKS
spring.kafka.ssl.trust-store-location=classpath:kafka/client.truststore.jks
spring.kafka.ssl.trust-store-password=changeit

# Disabilita il controllo rigoroso dell'hostname che a volte fallisce su cloud
spring.kafka.properties.ssl.endpoint.identification.algorithm=

# Credenziali (sostituisci USERNAME e PASSWORD con quelli di Aiven)

# spring.kafka.bootstrap-servers=kafka:9092 # Se usi docker-compose
# Impedisce al KafkaAdmin di bloccare l'avvio se il broker è offline
spring.kafka.admin.auto-create=false
