spring.application.name=WheelGame
server.port=8082

# PostgreSQL Database Configuration (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.hxvmcurwlsdxnhlfjycc
spring.datasource.password=TeamAfrica12345!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Per permettere la creazione delle tabelle automaticamente come su Oracle
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Disabilita prepared statements per compatibilità con il pooler (Supabase/PgBouncer)
spring.jpa.properties.hibernate.prepare_threshold=0
# Ottimizzazione per connessioni pooler (Supabase)
spring.datasource.hikari.maximum-pool-size=10
