spring.application.name=WheelGame
server.port=8082

# PostgreSQL Database Configuration (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.hxvmcurwlsdxnhlfjycc
spring.datasource.password=TeamAfrica12345!
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

# Per permettere la creazione delle tabelle automaticamente come su Oracle
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Disabilita prepared statements per compatibilità con il pooler (Supabase/PgBouncer)
spring.jpa.properties.hibernate.prepare_threshold=0
# Ottimizzazione per connessioni pooler (Supabase)
spring.datasource.hikari.maximum-pool-size=10

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=africa.wheel.wheelgame.dto

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Riduzione log per connessione Kafka fallita e tentativi
logging.level.org.apache.kafka.clients.NetworkClient=ERROR
spring.kafka.admin.fail-fast=false
spring.kafka.producer.retries=0
spring.kafka.enabled=false
